routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});


*/
Auth::routes();
include('routeadri.php');
/*
Route::group([

    'middleware' => 'api',
    'prefix' => 'auth'

], function ($router) {

    Route::post('login1', 'AuthController@login');
    Route::post('logout', 'AuthController@logout');
    Route::post('refresh', 'AuthController@refresh');
    Route::post('me', 'AuthController@me');

});
*/


Route::post('login1',['as'=>'login1', 'uses'=> 'AuthController@LoginViaAPI']);

Route::get('/home','HomeController@index')->name('home');
Route::get( '/', ['as'=>'home', 'uses'=> 'HomeController@index']);

///prospek
Route::get('/entry_prospek','ProspekController@entry_prospek_view')->name('entry_prospek');
Route::get('/data_prospek','ProspekController@data_prospek_view')->name('data_prospek');
Route::get('/daftar_prospek_baru','ProspekController@daftar_prospek_view')->name('daftar_prospek_baru');
Route::post('simulasi',['as'=>'simulasi', 'uses'=> 'ProspekController@simulasi']);
Route::post('daftar',['as'=>'daftar', 'uses'=> 'ProspekController@daftar']);
Route::get('/ubah_prospek','ProspekController@ubah_prospek');
Route::get('/kirim_pengajuan','ProspekController@kirim_pengajuan');
Route::post('pengajuan',['as'=>'pengajuan', 'uses'=> 'ProspekController@pengajuan']);

Route::get('/dokumen','ProspekController@dokumen');
Route::get('/tambah_dokumen','ProspekController@tambah_dokumen');
Route::get('/edit_dokumen','ProspekController@edit_dokumen');
Route::post('insert_dok',['as'=>'insert_dok', 'uses'=> 'ProspekController@insert_dok']);
Route::post('update_dok',['as'=>'update_dok', 'uses'=> 'ProspekController@update_dok']);


Route::get('/tambah_dokumen_entry_nasabah','EntryNasabahController@tambah_dokumen');
Route::post('insert_dok_entry_nasabah',['as'=>'insert_dok_entry_nasabah', 'uses'=> 'EntryNasabahController@insert_dok']);

//nasabah
Route::get('/entry_nasabah','NasabahController@entry_nasabah_view')->name('entry_nasabah');
Route::get('/daftar_nasabah_baru','NasabahController@daftar_nasabah_view')->name('daftar_nasabah_baru');


//menu
Route::get( '/dalam_proses', ['as'=>'dalam_proses', 'uses'=> 'HomeController@dalam_proses']);
//Route::get('/dalam_proses','HomeController@dalam_proses')->name('dalam_proses');
Route::get('/sudah_disetujui','HomeController@sudah_disetujui')->name('sudah_disetujui');
Route::get('/slik_checking','HomeController@slik_checking')->name('slik_checking');


//select
Route::get('/select/dati/{id}','HomeController@dati');

Route::get('/select/dashboard','HomeController@dashboard');


Route::resource('wilayah', 'WilayahController');
Route::post('/wilayah/tambah','WilayahController@tambah')->name('wilayah.tambah');
Route::post('/wilayah/delete/{id}','WilayahController@delete')->name('wilayah.delete');

Route::post('/prospek/delete/{id}','PPDPPController@delete')->name('PPDPP.delete');


Route::resource('user', 'UserController');
Route::post('/user/tambah','UserController@tambah')->name('user.tambah');
Route::post('/user/delete/{id}','UserController@delete')->name('user.delete');


Route::resource('developer', 'DeveloperController');
Route::post('/developer/tambah','DeveloperController@tambah')->name('developer.tambah');
Route::post('/developer/delete/{id}','DeveloperController@delete')->name('developer.delete');


Route::resource('residence', 'ResidenceController');
Route::post('/residence/tambah','ResidenceController@tambah')->name('residence.tambah');
Route::post('/residence/delete/{id}','ResidenceController@delete')->name('residence.delete');

//ppdpp
Route::get('/permohonan_uji','PPDPPController@permohonan_uji')->name('permohonan_uji');
Route::post('/permohonan_uji/add','PPDPPController@add_permohonan_uji')->name('permohonan_uji.add');
Route::get('/permohonan_uji/show/{id}/{type}','PPDPPController@edit_permohonan_uji')->name('permohonan_uji.show');

Route::get('/ceklis_agunan/show/{id}','PPDPPController@ceklis_agunan')->name('ceklis_agunan.show');
Route::post('/checklist_agunan/edit','PPDPPController@ceklis_agunan_edit')->name('permohonan_uji.edit');

Route::post('/ppdpp/upload','PPDPPController@upload_data_uji');



Route::post('/simulasi_angsuran','PPDPPController@simulasi_angsuran')->name('simulasi_angsuran');


Route::post('dks/update','PPDPPController@update_dks');
Route::get('/nasabah_uji','PPDPPController@nasabah_uji')->name('nasabah_uji');
Route::get('dks/table/{id}','PPDPPController@table');
Route::get('/lihat_nasabah','PPDPPController@lihat_nasabah')->name('lihat_nasabah');
Route::get('/lihat_nasabah_siap_cair','PPDPPController@lihat_nasabah_siap_cair')->name('lihat_nasabah_siap_cair');
Route::get('/lihat_nasabah_sudah_cair','PPDPPController@lihat_nasabah_sudah_cair')->name('lihat_nasabah_sudah_cair');
Route::get('/lihat_detail_nasabah_sudah_cair/{id}','PPDPPController@lihat_detail_nasabah_sudah_cair')->name('lihat_detail_nasabah_sudah_cair');
Route::get('/master_ppdpp','PPDPPController@master_ppdpp')->name('master_ppdpp');
Route::get('/detail_master_ppdpp/{id}','PPDPPController@detail_master_ppdpp')->name('detail_master_ppdpp');
Route::get('/jadwalAngsurByKTP','PPDPPController@jadwalAngsurByKTP');
Route::get('/cetakexcel','PPDPPController@cetakexcel');
Route::get('/cetakpdf','PPDPPController@cetakpdf');
Route::get('/cetakexcel1','PPDPPController@cetakexcel1');
Route::get('/cetakpdf1','PPDPPController@cetakpdf1');
Route::get('/jadwalAngsurByIDberkas','PPDPPController@jadwalAngsurByIDberkas');




///nasabah approve
Route::get('/slik_nasabah_approve','NasabahApproveController@slik');
Route::get('/appraisal_nasabah_approve','NasabahApproveController@appraisal');
Route::get('/analisa_nasabah_approve','NasabahApproveController@analisa');
Route::get('/sla_nasabah_approve','NasabahApproveController@sla');
Route::get('/ppdpp_nasabah_approve','NasabahApproveController@ppdpp');
Route::get('/proses_approval','NasabahApproveController@proses_approval');
Route::get('/reject','NasabahApproveController@reject');
Route::post('/approve','NasabahApproveController@approve');
Route::post('/simpan/approval','NasabahApproveController@approval');

//appraisal
Route::get('/detail_property_nasabah_approve','NasabahApproveController@detail_property');
Route::post( '/update_property_nasabah_approve', ['as'=>'update_property_nasabah_approve', 'uses'=> 'NasabahApproveController@update_property']);

//check ppdpp
Route::post( '/update_ppdpp_nasabah_approve', ['as'=>'update_ppdpp_nasabah_approve', 'uses'=> 'NasabahApproveController@update_ppdpp']);

//analisa
Route::post( '/update_analis_nasabah_approve', ['as'=>'update_analis_nasabah_approve', 'uses'=> 'NasabahApproveController@update_analis']);
Route::post( '/update_sp4k', ['as'=>'update_sp4k', 'uses'=> 'NasabahApproveController@update_sp4k']);
Route::post( '/kirim_data', ['as'=>'kirim_data', 'uses'=> 'NasabahApproveController@kirim_data']);
Route::get('/nasabah_approve','NasabahApproveController@index')->name('nasabah_approve');
Route::get('/edit_nasabah','NasabahApproveController@edit_nasabah')->name('edit_nasabah');
Route::get('/kirim_approve','NasabahApproveController@kirim_approve');
Route::get('/cetak_sp4k','NasabahApproveController@cetak_sp4k');


Route::post('/nasabah_approve/update_nasabah','NasabahApproveController@update')->name('nasabah_approve.update_nasabah');




//nasabah pra uji
Route::get('/nasabah_pra_uji','NasabahPraUjiController@index')->name('nasabah_pra_uji');
Route::get('/slik_nasabah_pra_uji','NasabahPraUjiController@slik');
Route::get('/appraisal_nasabah_pra_uji','NasabahPraUjiController@appraisal');
Route::get('/analisa_nasabah_pra_uji','NasabahPraUjiController@analisa');
Route::get('/sla_nasabah_pra_uji','NasabahPraUjiController@sla');
Route::get('/ppdpp_nasabah_pra_uji','NasabahPraUjiController@ppdpp');
Route::get('/detail_property_nasabah_pra_uji','NasabahPraUjiController@detail_property');
Route::post('/approve_nasabah_pra_uji','NasabahPraUjiController@approve');
Route::post('dks_nasabah_pra_uji/update','NasabahPraUjiController@update_dks');



//hasil pra uji
Route::get('/hasil_pra_uji','HasilPraUjiController@index')->name('hasil_pra_uji');
Route::get('/edit_hasil_pra_uji','HasilPraUjiController@edit_nasabah');
Route::get('/slik_hasil_pra_uji','HasilPraUjiController@slik');
Route::get('/appraisal_hasil_pra_uji','HasilPraUjiController@appraisal');
Route::get('/analisa_hasil_pra_uji','HasilPraUjiController@analisa');
Route::get('/sla_hasil_pra_uji','HasilPraUjiController@sla');
Route::get('/ppdpp_hasil_pra_uji','HasilPraUjiController@ppdpp');
Route::get('/detail_property_hasil_pra_uji','HasilPraUjiController@detail_property');
Route::post( '/kirim_data_hasil_pra_uji', ['as'=>'kirim_data_hasil_pra_uji', 'uses'=> 'HasilPraUjiController@kirim_data']);
Route::get('/kirim_hasil_pra_uji','HasilPraUjiController@kirim_approve');






//pra booking review
Route::get('/pra_booking_review','PrabookingreviewController@index')->name('pra_booking_review');

//pra booking review done
Route::get('/pra_booking_review_done','PrabookingreviewdoneController@index')->name('pra_booking_review_done');

//approval permohonan cair ppdpp
Route::get('/approval_permohonan_cair_ppdpp','ApprovalPermohonanCairPpdppController@index')->name('approval_permohonan_cair_ppdpp');

//update status siap cair
Route::get('/update_status_siap_cair','UpdateStatusSiapCairController@index')->name('update_status_siap_cair');



//approval permohonan cair cbs
Route::get('/approval_permohonan_cair_cbs','ApprovalPermohonanCairCbsController@index')->name('approval_permohonan_cair_cbs');



//akad
Route::get('/akad','AkadController@index')->name('akad');

app/User.php
<?php

namespace App;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    /*
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
   /*
    protected $hidden = [
        'password', 'remember_token',
    ];

    */

     // Rest omitted for brevity

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\UserModel;
use Illuminate\Support\Facades\Hash;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $param['data'] = \DB::select("SELECT * FROM users");
        if ($request->ajax()) {
            $view = view('user.index',$param)->renderSections();
            return json_encode($view);
        }
        return view('master.master')->nest('child', 'user.index',$param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('master.master')->nest('child', 'user.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
    }

     public function tambah(Request $request)
    {
        if ($request->input('type') == "normal") {
            $datan = new UserModel();
        }else{
            $datan = UserModel::find($request->input('id'));
        }
         $datan->created_date = date('Y-m-d');

         $datan->u_first_name = $request->input('nama');
         $datan->u_last_name = $request->input('nama');

         $datan->username = $request->input('username');
         $datan->email = $request->input('email');
         $datan->id_ktp = $request->input('ktp');
         $datan->u_phone_no = $request->input('phone');

         if ($request->input('password')!= "") {
             $datan->password = Hash::make($request->input('password'));
         }
         
         $datan->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $param['data'] = collect(\DB::select("SELECT * FROM users where id = '".$id."'"))->first();

        return view('master.master')->nest('child', 'user.form',$param);
    }

    public function delete($id)
    {
        $data = UserModel::find($id);
        $data->delete();

        // return json_encode(['rc' => 0, 'rm' => 'Data Berhasil']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/action.blade.php
<script>
    
function TambahDataBaru() {
    console.log("tambahBaru");

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    
$.ajax({
        type: "POST",
        url: base_url + '/user/tambah',
        data: {
            type: $('#type').val(),
            email: $('#email').val(),
            phone: $('#phone').val(),
            ktp: $('#ktp').val(),
            username: $('#username').val(),
            password: $('#password').val(),
            nama: $('#nama').val(),
            id: $('#id').val()
            

        },
        beforeSend: function () {
        },
        success: function (msg) {

        }
    }).done(function (msg) {
        window.location.href = base_url + '/user';

    }).fail(function (msg) {

    });
    
}



function HapusDataBaru(id) {
    swal({
        title: "Hapus",
        text: "Anda Yakin akan Hapus?",
        type: "info",
        showCancelButton: true,
        confirmButtonColor: "#e6b034",
        confirmButtonText: "Ya",
        cancelButtonText: "Tidak",
        closeOnConfirm: false,
        closeOnCancel: false
    }, function (isConfirm) {
        if (isConfirm) {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "POST",
                url: base_url + '/user/delete/' + id,
                data: {
                    id: id
                },
                beforeSend: function () {
                },
                success: function (msg) {
                    console.log(msg);
                    swal({
                        title: "Informasi",
                        text: "berhasil Terhapus",
                        type: "info",
                        confirmButtonColor: "#8cd4f5",
                        confirmButtonText: "Ya",
                        closeOnConfirm: false
                    }, function (isConfirm) {
                        if (isConfirm) {
                            location.reload();
                        }
                    });

                }
            }).done(function (msg) {

            }).fail(function (msg) {
                swal("Terjadi Kesalahan! ");
            });

        } else {
            swal("Dibatalkan!");
        }
    });
}

</script>

resources/views/user/form.blade.php
@section('content')

@php
    if(isset($data)){
        $id = $data->id;

        $u_first_name = $data->u_first_name;
        $username = $data->username;
        $email = $data->email;
        $id_ktp = $data->id_ktp;
        $u_phone_no = $data->u_phone_no;
        $type = 'update';
    }else {
        $id = '';
        $u_first_name = '';
        $username = '';
        $email = '';
        $id_ktp = '';
        $u_phone_no = '';
        $type = 'normal';
        
    }
@endphp
<div class="c-forms"> 
            <a class="i-button no-margin" href="{{route('user.index')}}">Kembali</a>   

    <div class="box-element" style="
    margin-top: 20px;
">
        <form id="form_tambah_data">
            
        <input type="hidden" name="id" id="id" value="{{$id}}">

        <input type="hidden" name="type" id="type" value="{{$type}}">

              <div class="i-label">
                <label for="text_field">Nama</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    <input value="{{$u_first_name}}" type="text" name="nama" id="nama" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>


            <div class="i-label">
                <label for="text_field">Email</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    <input value="{{$email}}" type="text" name="email" id="email" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>

             <div class="i-label">
                <label for="text_field">Phone Number</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    <input value="{{$u_phone_no}}" type="text" name="phone" id="phone" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>

             <div class="i-label">
                <label for="text_field">KTP</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    <input value="{{$id_ktp}}" type="text" name="ktp" id="ktp" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>

              <div class="i-label">
                <label for="text_field">Username</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    {{-- onkeyup="convertToNum(this)"  --}}
                    <input value="{{$username}}" type="text" name="username" id="username" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>

              <div class="i-label">
                <label for="text_field">Password</label>
            </div>                                  
            <div class="section-right">
                <div class="section-input">
                    {{-- onkeyup="convertToNum(this)"  --}}
                    <input value="" type="password" name="password" id="password" class="i-text required"></input></div>
            </div>
            <div class="i-divider"></div>
            <div class="clearfix"></div>
            
            

        <input type="button" style="margin: 20px !important;" onclick="TambahDataBaru();" class="i-button no-margin" value="Simpan" />

        </form>
    </div>
</div>
        
   

@include('user.action')
@endsection
@section('script')
    <script type="text/javascript" src="{{ asset('js/content/dks.js') }}"></script>
@stop

resources/views/user/index.blade.php
@section('content')
<div class="c-forms">       
    <div class="box-element">
        <div class="box-head-light"><span class="forms-16"></span><h3>Daftar User</h3><a href="" class="collapsable"></a></div>
        <div class="box-content no-padding">

              <div class="right">
                <a href="{{route('user.create')}}"><input type="button" class="icon16-button" value="Tambah Baru"></a>
                {{-- <a href="#"><input type="button" name="submit" id="show-dks" class="i-button no-margin" value="Tandai Batch" /></a> --}}
            </div>
            
        
           <table cellpadding="0" cellspacing="0" border="0" class="display" id="t_user">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Nomor Telepon</th>
                    <th>KTP</th>
                    <th style="width:200px;">Action</th>
                </tr>
            </thead>
            <tbody>
                @if($data)
                    @foreach($data as $item)
                        <tr style="height: 40px;">        
                            <td style="padding:15px;" align="center">{{$item->id}}</td>
                            <td style="padding:15px;" align="center">{{$item->username}}</td>
                            <td style="padding:15px;" align="center">{{$item->email}}</td>
                            <td style="padding:15px;" align="center">{{$item->u_phone_no}}</td>
                            <td style="padding:15px;" align="center">{{$item->id_ktp}}</td>
                            <td>
                             <a href="{{route('user.edit',$item->id)}}"><input type="button" class="icon16-button" value="Edit"></a>
                            <a onclick="HapusDataBaru({{$item->id}})"><input type="button" class="icon16-button" value="Hapus"></a>

                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
        </div>
    </div>
</div>



@include('user.action')
@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/content/dks.js') }}"></script>
<script>
var t_user = $('#t_user').dataTable({
    "sPaginationType": "full_numbers"   
});
</script>
@stop